/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AukceRouteImport } from './routes/aukce'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InzeratyRouteImport } from './routes/inzeraty'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AukceRoute = AukceRouteImport.update({
  id: '/aukce',
  path: '/aukce',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InzeratyRoute = InzeratyRouteImport.update({
  id: '/inzeraty',
  path: '/inzeraty',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aukce': typeof AukceRoute
  '/cenik': typeof CenikRoute
  '/dashboard': typeof DashboardRoute
  '/inzeraty': typeof InzeratyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aukce': typeof AukceRoute
  '/cenik': typeof CenikRoute
  '/dashboard': typeof DashboardRoute
  '/inzeraty': typeof InzeratyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aukce': typeof AukceRoute
  '/cenik': typeof CenikRoute
  '/dashboard': typeof DashboardRoute
  '/inzeraty': typeof InzeratyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aukce' | '/cenik' | '/dashboard' | '/inzeraty'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aukce' | '/cenik' | '/dashboard' | '/inzeraty'
  id: '__root__' | '/' | '/aukce' | '/cenik' | '/dashboard' | '/inzeraty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AukceRoute: typeof AukceRoute
  CenikRoute: typeof CenikRoute
  DashboardRoute: typeof DashboardRoute
  InzeratyRoute: typeof InzeratyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aukce': {
      id: '/aukce'
      path: '/aukce'
      fullPath: '/aukce'
      preLoaderRoute: typeof AukceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inzeraty': {
      id: '/inzeraty'
      path: '/inzeraty'
      fullPath: '/inzeraty'
      preLoaderRoute: typeof InzeratyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AukceRoute: AukceRoute,
  CenikRoute: CenikRoute,
  DashboardRoute: DashboardRoute,
  InzeratyRoute: InzeratyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
